### ISSUE TITLE
installing plugin error

### ISSUE THREAD

**Issue by n3roGit** [mwittig/pimatic-amazing-dash-button#15]
458 info install cap@0.1.2
459 verbose unsafe-perm in lifecycle true
460 info cap@0.1.2 Failed to exec install script
461 verbose unlock done using /opt/pimatic-app/.npm/_locks/cap-5f526ab8aca0e2d9.lock for /opt/pimatic-app/node_modules/pimatic-amazing-dash-button/node_modules/cap
462 verbose about to build /opt/pimatic-app/node_modules/pimatic-amazing-dash-button
463 verbose unlock done using /opt/pimatic-app/.npm/_locks/pimatic-amazing-dash-but-52828f536dd868cb.lock for /opt/pimatic-app/node_modules/pimatic-amazing-dash-button
464 verbose stack Error: cap@0.1.2 install: `node-gyp rebuild`
464 verbose stack Exit status 1
464 verbose stack     at EventEmitter.<anonymous> (/opt/pimatic-app/node_modules/pimatic/node_modules/npm/lib/utils/lifecycle.js:217:16)
464 verbose stack     at emitTwo (events.js:87:13)
464 verbose stack     at EventEmitter.emit (events.js:172:7)
464 verbose stack     at ChildProcess.<anonymous> (/opt/pimatic-app/node_modules/pimatic/node_modules/npm/lib/utils/spawn.js:24:14)
464 verbose stack     at emitTwo (events.js:87:13)
464 verbose stack     at ChildProcess.emit (events.js:172:7)
464 verbose stack     at maybeClose (internal/child_process.js:854:16)
464 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
465 verbose pkgid cap@0.1.2
466 verbose cwd /opt/pimatic-app
467 error Linux 4.4.59+
468 error argv "/usr/local/bin/node" "/opt/pimatic-app/node_modules/pimatic/ppm.js" "install" "pimatic-amazing-dash-button@0.9.14" "--unsafe-perm"
469 error node v4.6.2
470 error npm  v2.15.12
471 error code ELIFECYCLE
472 error cap@0.1.2 install: `node-gyp rebuild`
472 error Exit status 1
473 error Failed at the cap@0.1.2 install script 'node-gyp rebuild'.
473 error This is most likely a problem with the cap package,
473 error not with npm itself.
473 error Tell the author that this fails on your system:
473 error     node-gyp rebuild
473 error You can get information on how to open an issue for this project with:
473 error     npm bugs cap
473 error Or if that isn't available, you can get their info via:
473 error
473 error     npm owner ls cap
473 error There is likely additional logging output above.

**Comment by mwittig** [comment]
Did you install libpcap-dev as advised in the README?

n3ro <notifications@github.com> schrieb am Do. 26. Juli 2018 um 23:24:

**Comment by n3roGit** [comment]
yes

**Comment by mwittig** [comment]
Did you install `libpcap0.8-dev` or `libpcap-dev`?
Should be `libpcap-dev` which automatically installs `libpcap0.8` and `libpcap0.8-dev` amongst other dependencies. Note, both libpcap and libpcap-dev packages are required

**Comment by mwittig** [comment]
Other things to check:
* `python --version`.  Should be `Python 2.7.x`. `Python 3.x.x` is not supported.
* `gcc --version`. Should be `4.9.x`

**Comment by n3roGit** [comment]
python was the solution! BIG THX to you!

**Comment by mwittig** [comment]
Excellent! I am glad it is working for you now! 

I have revised the installation section as part of README, acccordingly.
