### ISSUE TITLE
discover filter

### ISSUE THREAD

**Issue by n3roGit** [mwittig/pimatic-amazing-dash-button#2]
please add a MAC discovery filter with "AC:63:BE:_". at the moment my fire hd with "A0:02:DC:_" would be detected as dash :D

**Comment by mwittig** [comment]
Thanks for your report. "AC:63:BE:" is already part of the list of filtered vendor ids. Actually, the code filters for all vendor ids, registered with IEEE by Amazon. Currently, there is no info on which subset of vendor ids is used for dash-buttons.  See also https://github.com/mwittig/pimatic-amazing-dash-button/blob/master/amazing-dash-button.coffee#L67-L71

Regarding vendor id AC:63:BE: doesn't auto discovery work for your dash button? This would be strange as it is working for me and my dash-button has the same MAC vendor id. Does your dash-button work at all with the plugin? If not, you may need to provide the IP-address assigned to network interface which should be used to capture dash-button ARP requests. See also https://github.com/mwittig/pimatic-amazing-dash-button#plugin-configuration

**Comment by n3roGit** [comment]
Yes it works with auto discover :)

**Comment by mwittig** [comment]
OK, that's great. So, I am closing this ticket now. Please re-open if you want to follow up on this.

I'll add a note to README, that auto discovery will detected "false positives" if other Amazon devices are on the network. Hopefully, there will be some some information available soon about the subset of vendor ids used for dash-buttons.

**Comment by mwittig** [comment]
If you like this plugin, please consider &#x2605; starring [the project on github](https://github.com/mwittig/pimatic-amazing-dash-button). Thanks!
