### ISSUE TITLE
Button not working with Fritz!Repeater

### ISSUE THREAD

**Issue by ccvh** [mwittig/pimatic-amazing-dash-button#5]
I've set up the pimatic-amazing-dash and everything worked out fine. Because of the bad wlan range of the fritzbox6490, i've set up a range extender (fritz! as well), which is now nearer to the pimatic dash as the router itself. 
If i press the button now - nothing happens. I think the problem is, that a) the dash button does recognise, that the repeater is another device or b) the dash connects through the repeater, but isn't recognised anymore by the pimatic-plugin. If i unplug the repeater, everything works out.

**Comment by mwittig** [comment]
How did you connect your Raspi with the repeater? Wireless or do you use network cable?
- Wireless case: That's bad news. Apparently the your repeater does not route ARP requests as it should. I am using a Fritzbox 7390 as a repeater which works fine for me. One thing you check and try is the following:
  - On the access router (Fritzbox) admin UI goto WLAN > Sicherheit and make sure the checkbox "WLAN Geräte dürfen untereinander kommunizieren" is checked.  (see screenshot below). If not checked turn it on and save the configuration.
  - Now check the same for the repeater.
- Wired case: If you connect via wire the Raspi is using a different network interface and you may need to specify that as part of the configuration.

![image](https://cloud.githubusercontent.com/assets/6117742/20208293/6c9cacae-a7ed-11e6-9a01-a589e55e67f3.png)

**Comment by ccvh** [comment]
My Raspi is connected via cable to the router. What do i need to configure then?

**Comment by mwittig** [comment]
As part of the plugin configuration you need to set the IP address assigned to network the interface. You check the assigned IP address by using `ifconfig`. The interface name typically is `eth0`. After having set the plugin configuration don't forget to restart pimatic. If this still doesn't work please check the configuration settings I have mentioned for the "wireless" case on the router and repeater.

![image](https://cloud.githubusercontent.com/assets/6117742/20210409/bd96e848-a7f9-11e6-9348-919f100ed843.png)

![image](https://cloud.githubusercontent.com/assets/6117742/20210510/3fac40ee-a7fa-11e6-8e90-41eddbbd3eff.png)

**Comment by mwittig** [comment]
@ccvh Did you get a chance to trial the suggested changes?

**Comment by ccvh** [comment]
@mwittig Sorry, i was a bit busy because of my work and we had some waterpipes damaged in our appartmend. 
I just reconfigured the repeater, as well as the plugin and it seems to woork oob now! Sorry for the long latency, but i think this issue can be closed.
